# Generated by Django 5.2.7 on 2026-03-01

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0002_charity_user_texttemplate_videotemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("THANK_YOU", "Thank You Video"),
                            ("DIRECT_EMAIL", "Direct Email Video"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "video_mode",
                    models.CharField(
                        choices=[
                            ("TEMPLATE", "Template Video"),
                            ("PERSONALIZED", "Personalized Video"),
                        ],
                        max_length=32,
                    ),
                ),
                ("gratitude_cooldown_days", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="charity.charity",
                    ),
                ),
                (
                    "gratitude_video_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gratitude_campaigns",
                        to="charity.videotemplate",
                    ),
                ),
                (
                    "text_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="charity.texttemplate",
                    ),
                ),
                (
                    "video_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="charity.videotemplate",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donors",
                        to="charity.charity",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("charity", "email")}},
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("THANK_YOU", "Thank You Video"),
                            ("DIRECT_EMAIL", "Direct Email Video"),
                        ],
                        default="THANK_YOU",
                        max_length=32,
                    ),
                ),
                ("donated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(default="CSV", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="charity.charity",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="charity.donor",
                    ),
                ),
            ],
            options={"ordering": ["-donated_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="VideoSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("THANK_YOU", "Thank You Video"),
                            ("DIRECT_EMAIL", "Direct Email Video"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "send_kind",
                    models.CharField(
                        choices=[
                            ("TEMPLATE", "Template"),
                            ("PERSONALIZED", "Personalized"),
                            ("GRATITUDE", "Gratitude"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SENT", "Sent"), ("FAILED", "Failed")],
                        default="SENT",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("video_file", models.FilePathField(max_length=1024)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_sends",
                        to="charity.campaign",
                    ),
                ),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_sends",
                        to="charity.charity",
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_sends",
                        to="charity.donation",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_sends",
                        to="charity.donor",
                    ),
                ),
            ],
            options={"ordering": ["-sent_at", "-created_at"]},
        ),
    ]
