# Generated by Django 5.2.7 on 2025-11-11 14:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0003_donationjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationjob",
            name="batch_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="donationjob",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donationjob",
            name="task_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name="donationjob",
            index=models.Index(fields=["status"], name="charity_don_status_bf58bc_idx"),
        ),
        migrations.AddIndex(
            model_name="donationjob",
            index=models.Index(fields=["email"], name="charity_don_email_efa94b_idx"),
        ),
        migrations.AddIndex(
            model_name="donationjob",
            index=models.Index(fields=["created_at"], name="charity_don_created_07206b_idx"),
        ),
    ]
