# Generated by Django 5.1.6 on 2025-12-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0005_donationjob_generation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationjob",
            name="fake_views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="donationjob",
            name="real_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
