# Generated by Django 5.1.6 on 2025-12-23 16:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0012_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("appeal_code", models.CharField(max_length=50)),
                ("appeal_reference", models.CharField(max_length=100)),
                (
                    "appeal_type",
                    models.CharField(
                        choices=[("Donation", "Donation"), ("Raffle", "Raffle")],
                        default="Donation",
                        max_length=20,
                    ),
                ),
                ("appeal_start", models.DateField()),
                ("appeal_end", models.DateField()),
                ("open_date", models.DateField()),
                ("close_date", models.DateField()),
                ("hgv_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("lgv_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("campaign_manager_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("closed", "Closed")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="charity.charity",
                    ),
                ),
                ("package_codes", models.ManyToManyField(blank=True, to="charity.packagecode")),
            ],
        ),
        migrations.CreateModel(
            name="CampaignField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("dropdown", "Dropdown"),
                            ("radio", "Radio"),
                            ("checkbox", "Checkbox"),
                            ("textarea", "Textarea"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Comma-separated options for dropdown/radio/checkbox",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="charity.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
