# Generated by Django 5.1.6 on 2026-01-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0022_donationjob_media_type_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationjob',
            name='fake_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donationjob',
            name='real_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
