# Generated by Django 5.1.6 on 2026-01-05 18:13

import charity.utils.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0023_donationjob_fake_clicks_donationjob_real_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=charity.utils.media_utils.get_client_media_path),
        ),
        migrations.AlterField(
            model_name='charity',
            name='thank_you_card',
            field=models.ImageField(blank=True, null=True, upload_to=charity.utils.media_utils.get_client_media_path),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='video_file',
            field=models.FileField(upload_to=charity.utils.media_utils.get_client_media_path),
        ),
    ]
