# Generated by Django 5.1.6 on 2026-01-08 13:30

from django.db import migrations, models

import charity.utils.media_utils


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0024_alter_charity_logo_alter_charity_thank_you_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charity",
            name="base_video_file",
            field=models.FileField(
                blank=True, null=True, upload_to=charity.utils.media_utils.get_client_media_path
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="elevenlabs_voice_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="charity",
            name="language",
            field=models.CharField(default="en", max_length=20),
        ),
        migrations.AddField(
            model_name="charity",
            name="voiceover_script",
            field=models.TextField(
                blank=True,
                help_text="Default script with placeholders {{donor_name}}, {{donation_amount}}",
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="watermark_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
