# Generated by Django 5.1.6 on 2026-01-12 06:52

import charity.utils.media_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0025_charity_base_video_file_charity_elevenlabs_voice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationbatch',
            name='text_template',
        ),
        migrations.RemoveField(
            model_name='videotemplate',
            name='charity',
        ),
        migrations.RemoveField(
            model_name='donationbatch',
            name='video_template',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='donationjob',
            old_name='amount',
            new_name='donation_amount',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='account_manager',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='auto_unsubscribe_enabled',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='base_video_file',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='campaign_name',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='client_status',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='data_retention_days',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='default_cta_url',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='elevenlabs_voice_id',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='email_api_key',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='gdpr_compliant',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='language',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='max_concurrent_batches',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='max_emails_per_day',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='max_retry_attempts',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='max_videos_per_day',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='reply_to_email',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='retry_failed_jobs',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='terms_accepted',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='thank_you_card',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='track_clicks',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='track_unsubscribes',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='track_views',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='voiceover_script',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='watermark_enabled',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='website',
        ),
        migrations.RemoveField(
            model_name='donationjob',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='donationjob',
            name='name',
        ),
        migrations.AddField(
            model_name='campaign',
            name='video_template_override',
            field=models.FileField(blank=True, help_text='Override Client default video', null=True, upload_to=charity.utils.media_utils.get_client_media_path),
        ),
        migrations.AddField(
            model_name='campaign',
            name='voiceover_script_override',
            field=models.TextField(blank=True, help_text='Override Client default script'),
        ),
        migrations.AddField(
            model_name='charity',
            name='contact_email',
            field=models.EmailField(default='contact@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charity',
            name='default_template_video',
            field=models.FileField(blank=True, help_text='fallback MP4', null=True, upload_to=charity.utils.media_utils.get_client_media_path),
        ),
        migrations.AddField(
            model_name='charity',
            name='default_voice_id',
            field=models.CharField(blank=True, help_text='Default ElevenLabs voice ID', max_length=128),
        ),
        migrations.AddField(
            model_name='charity',
            name='default_voiceover_script',
            field=models.TextField(blank=True, help_text='Default script with placeholders {{donor_name}}, {{donation_amount}}, {{organization_name}}'),
        ),
        migrations.AddField(
            model_name='charity',
            name='organization_name',
            field=models.CharField(default='Organization Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationjob',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='charity.campaign'),
        ),
        migrations.AddField(
            model_name='donationjob',
            name='charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='charity.charity'),
        ),
        migrations.AddField(
            model_name='donationjob',
            name='donor_name',
            field=models.CharField(default='Donor', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationjob',
            name='donation_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_deprecated', to='charity.donationbatch'),
        ),
        migrations.AlterField(
            model_name='donationjob',
            name='media_type_override',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TextTemplate',
        ),
        migrations.DeleteModel(
            name='VideoTemplate',
        ),
    ]
