# Generated by Django 5.1.6 on 2026-01-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0027_remove_campaign_campaign_manager_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='appeal_type',
            field=models.CharField(choices=[('WithThanks', 'WithThanks'), ('VDM', 'VDM')], default='Donation', max_length=20),
        ),
    ]
