# Generated by Django 5.1.6 on 2026-01-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0029_alter_donationjob_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_personalized',
            field=models.BooleanField(default=False, help_text='Use TTS and personalized stitching (WithThanks only)'),
        ),
    ]
