# Generated by Django 5.1.6 on 2026-01-14 16:56

from django.db import migrations, models

import charity.utils.media_utils


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0030_campaign_is_personalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="charity",
            name="gratitude_card",
            field=models.FileField(
                blank=True,
                help_text="Gratitude card (Video or Image)",
                null=True,
                upload_to=charity.utils.media_utils.get_client_media_path,
            ),
        ),
    ]
