# Generated by Django 5.1.6 on 2026-01-29 13:26

import charity.utils.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0034_emailtracking_video_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='charity_video',
            field=models.FileField(blank=True, help_text='Main Campaign Video (VDM Appeal)', null=True, upload_to=charity.utils.media_utils.get_client_media_path),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gratitude_video',
            field=models.FileField(blank=True, help_text='Gratitude Video (WithThanks Appeal)', null=True, upload_to=charity.utils.media_utils.get_client_media_path),
        ),
    ]
