# Generated by Django 5.1.6 on 2026-02-14 09:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0038_charity_blackbaud_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_events', to='charity.charity')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_events', to='charity.donationjob')),
            ],
        ),
        migrations.CreateModel(
            name='WatchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_seconds_watched', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to='charity.donationjob')),
            ],
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('spam_complaint', 'Spam Complaint'), ('sent', 'Sent')], max_length=50)),
                ('provider_status', models.CharField(blank=True, max_length=255, null=True)),
                ('bounce_reason', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='charity.donationbatch')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='charity.campaign')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='charity.donationjob')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='charity_ema_event_t_9d5fd5_idx'), models.Index(fields=['job'], name='charity_ema_job_id_a64da0_idx'), models.Index(fields=['campaign'], name='charity_ema_campaig_c4844f_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('generated', 'Generated'), ('play_started', 'Play Started'), ('25_percent', '25% Completion'), ('50_percent', '50% Completion'), ('75_percent', '75% Completion'), ('100_percent', '100% Completion'), ('watch_heartbeat', 'Watch Heartbeat')], max_length=50)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_events', to='charity.campaign')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_events', to='charity.donationjob')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_events', to='charity.watchsession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='charity_vid_event_t_371d7a_idx'), models.Index(fields=['job'], name='charity_vid_job_id_7a17c2_idx')],
            },
        ),
    ]
