# Generated by Django 5.1.6 on 2026-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0039_unsubscribeevent_watchsession_emailevent_videoevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailevent",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="videoevent",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="emailevent",
            name="charity_ema_event_t_9d5fd5_idx",
        ),
        migrations.RemoveIndex(
            model_name="videoevent",
            name="charity_vid_event_t_371d7a_idx",
        ),
        migrations.RenameField(
            model_name="emailevent",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="unsubscribeevent",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="videoevent",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="watchsession",
            old_name="started_at",
            new_name="created_at",
        ),
        migrations.AddIndex(
            model_name="emailevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="charity_ema_event_t_a88963_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="charity_vid_event_t_afa2f3_idx"
            ),
        ),
    ]
