# Generated by Django 5.1.6 on 2026-02-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0040_alter_emailevent_options_alter_videoevent_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("setup", "Set Up & Management"),
                            ("production", "Video Production"),
                            ("gratitude", "Gratitude Cards"),
                            ("postage", "Postage & Printing"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_tiered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="charity.invoice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="charity.invoiceservice",
                    ),
                ),
            ],
        ),
    ]
