# Generated by Django 5.1.6 on 2026-02-19 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0044_remove_charity_billing_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="appeal_reference",
        ),
    ]
