# Generated by Django 5.1.6 on 2026-02-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0047_charity_billing_address_charity_billing_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('total_opens', models.PositiveIntegerField(default=0)),
                ('unique_opens', models.PositiveIntegerField(default=0)),
                ('total_unsubs', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_video_views', models.PositiveIntegerField(default=0)),
                ('avg_watch_duration', models.FloatField(default=0.0)),
                ('total_watch_time', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='emailevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='videoevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='emailevent',
            name='charity_ema_job_id_a64da0_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailevent',
            name='charity_ema_event_t_a88963_idx',
        ),
        migrations.RemoveIndex(
            model_name='videoevent',
            name='charity_vid_job_id_7a17c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='videoevent',
            name='charity_vid_event_t_afa2f3_idx',
        ),
        migrations.RenameField(
            model_name='emailevent',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='videoevent',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='emailevent',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='emailevent',
            name='bounce_reason',
        ),
        migrations.RemoveField(
            model_name='emailevent',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='emailevent',
            name='provider_status',
        ),
        migrations.RemoveField(
            model_name='emailevent',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='videoevent',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('THANKYOU', 'Thank You'), ('VDM', 'Video Direct Mail (VDM)')], default='THANKYOU', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='videoevent',
            name='cloudflare_video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videoevent',
            name='completion_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoevent',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoevent',
            name='watch_duration',
            field=models.FloatField(default=0.0, help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='emailevent',
            name='event_type',
            field=models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('OPEN', 'Open'), ('CLICK', 'Click'), ('UNSUB', 'Unsubscribe'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('sent', 'Sent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='videoevent',
            name='event_type',
            field=models.CharField(choices=[('PLAY', 'Play'), ('PROGRESS', 'Progress'), ('COMPLETE', 'Complete'), ('generated', 'Generated'), ('play_started', 'Play Started'), ('25_percent', '25% Completion'), ('50_percent', '50% Completion'), ('75_percent', '75% Completion'), ('100_percent', '100% Completion')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='charity_ema_event_t_9d5fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='videoevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='charity_vid_event_t_371d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='videoevent',
            index=models.Index(fields=['campaign'], name='charity_vid_campaig_dafcd3_idx'),
        ),
        migrations.AddField(
            model_name='campaignstats',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='charity.campaign'),
        ),
    ]
