# Generated by Django 5.1.6 on 2026-02-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0049_campaignstats_bounce_rate_campaignstats_click_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="resend_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
