# Generated by Django 5.1.6 on 2026-02-28 20:27

import charity.utils.media_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0051_service_alter_invoicelineitem_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(choices=[('setup', 'Set Up & Management'), ('production', 'Video Production'), ('gratitude', 'Gratitude Cards'), ('postage', 'Postage & Printing'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_tiered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='emailtracking',
            old_name='completion_time',
            new_name='played_at',
        ),

        migrations.RemoveField(
            model_name='charity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailtracking',
            name='play_time',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='email_opened_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='email_sent_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='resend_id',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='video_template_override',
            field=models.FileField(blank=True, help_text='Override the default template video', null=True, upload_to=charity.utils.media_utils.get_client_media_path),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='voiceover_script_override',
            field=models.TextField(blank=True, help_text='Override the default charity voiceover script'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.invoiceservice'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
