# Generated by Django 6.0.2 on 2026-03-02 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0055_stripe_fields_and_event_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Script with {{donor_name}}, {{donation_amount}}, {{charity}}, {{campaign_name}} placeholders",
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(blank=True, help_text="ElevenLabs voice ID", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("video_file", models.FileField(upload_to="video_templates/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="total_failed",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="total_sent",
        ),
        migrations.AddField(
            model_name="campaign",
            name="gratitude_cooldown_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Days within which a repeat donation triggers a gratitude video instead",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="video_mode",
            field=models.CharField(
                choices=[
                    ("PERSONALIZED", "Personalized (TTS + stitch)"),
                    ("TEMPLATE", "Template-only (pre-rendered)"),
                ],
                default="PERSONALIZED",
                help_text="How the video is produced for the API pipeline",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_type",
            field=models.CharField(
                choices=[("THANK_YOU", "Thank You"), ("VDM", "Video Direct Mail")],
                default="THANK_YOU",
                help_text="API pipeline campaign type",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donors",
                        to="charity.charity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("donated_at", models.DateTimeField()),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[("THANK_YOU", "Thank You"), ("VDM", "Video Direct Mail")],
                        default="THANK_YOU",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="API", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="charity.charity",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="charity.donor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="text_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Voiceover script template (API pipeline)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="charity.texttemplate",
            ),
        ),
        migrations.CreateModel(
            name="VideoSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[("THANK_YOU", "Thank You"), ("VDM", "Video Direct Mail")],
                        default="THANK_YOU",
                        max_length=20,
                    ),
                ),
                (
                    "send_kind",
                    models.CharField(
                        choices=[
                            ("PERSONALIZED", "Personalized"),
                            ("TEMPLATE", "Template"),
                            ("GRATITUDE", "Gratitude"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("video_file", models.CharField(blank=True, max_length=512)),
                ("stream_video_id", models.CharField(blank=True, max_length=255)),
                ("stream_playback_url", models.URLField(blank=True, max_length=512)),
                ("stream_thumbnail_url", models.URLField(blank=True, max_length=512)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_send_logs",
                        to="charity.campaign",
                    ),
                ),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_send_logs",
                        to="charity.charity",
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_send_logs",
                        to="charity.donation",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_send_logs",
                        to="charity.donor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="gratitude_video_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Gratitude video template (API pipeline)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gratitude_campaigns",
                to="charity.videotemplate",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="video_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Base video template (API pipeline)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="charity.videotemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(fields=["charity", "email"], name="charity_don_charity_7d3977_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="donor",
            unique_together={("charity", "email")},
        ),
        migrations.AddIndex(
            model_name="videosendlog",
            index=models.Index(fields=["charity", "donor"], name="charity_vid_charity_53ff52_idx"),
        ),
        migrations.AddIndex(
            model_name="videosendlog",
            index=models.Index(fields=["status"], name="charity_vid_status_41d78d_idx"),
        ),
    ]
