# Generated by Django 6.0.2 on 2026-03-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0056_stage3_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationjob',
            name='fake_clicks',
        ),
        migrations.RemoveField(
            model_name='donationjob',
            name='fake_views',
        ),
        migrations.DeleteModel(
            name='UnsubscribeEvent',
        ),
    ]
