# Generated by Django 6.0.2 on 2026-03-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0057_cleanup_remove_fake_metrics_and_unsubscribe_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with Errors"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=25,
            ),
        ),
    ]
