# Generated by Django 6.0.2 on 2026-03-03 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0059_donationjob_dedup_index_and_decimal_amount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PackageCode",
        ),
    ]
