# Generated by Django 6.0.2 on 2026-03-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0060_remove_packagecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_hosted_url',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_pdf_url',
        ),
        migrations.AddField(
            model_name='charity',
            name='additional_emails',
            field=models.TextField(blank=True, help_text='Comma-separated default CC email addresses for invoice delivery', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_billing_emails',
            field=models.TextField(blank=True, help_text='Comma-separated CC email addresses for this invoice', null=True),
        ),
    ]
