# Generated by Django 6.0.2 on 2026-03-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0061_remove_stripe_add_multi_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationjob",
            name="resend_message_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID returned by Resend API after email dispatch; used to correlate webhook events",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SENT", "Sent"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed"),
                    ("BOUNCED", "Bounced"),
                    ("OPEN", "Open"),
                    ("CLICK", "Click"),
                    ("UNSUB", "Unsubscribe"),
                    ("COMPLAINED", "Complained / Spam"),
                    ("SUPPRESSED", "Suppressed"),
                ],
                max_length=50,
            ),
        ),
    ]
