# Generated by Django 6.0.2 on 2026-03-04 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0063_add_cta_fields_to_campaign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="is_personalized",
        ),
    ]
