# Generated by Django 6.0.2 on 2026-03-13 19:20

import charity.utils.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0069_campaign_vdm_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image shown in donor emails and linked to the video landing page', null=True, upload_to=charity.utils.media_utils.get_client_media_path),
        ),
    ]
