# Generated by Django 6.0.2 on 2026-03-13 21:15

import charity.utils.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0073_rename_campaign_client_to_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='charity_video',
            field=models.FileField(blank=True, help_text='Main Campaign Video (VDM Campaign)', null=True, upload_to=charity.utils.media_utils.get_charity_media_path),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='email_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image shown in donor emails and linked to the video landing page', null=True, upload_to=charity.utils.media_utils.get_charity_media_path),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='gratitude_video',
            field=models.FileField(blank=True, help_text='Gratitude Video (Thank You Campaign — sent to repeat donors within cooldown window)', null=True, upload_to=charity.utils.media_utils.get_charity_media_path),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='video_template_override',
            field=models.FileField(blank=True, help_text='Override the default template video', null=True, upload_to=charity.utils.media_utils.get_charity_media_path),
        ),
        migrations.AlterField(
            model_name='charity',
            name='default_template_video',
            field=models.FileField(blank=True, help_text='fallback MP4', null=True, upload_to=charity.utils.media_utils.get_charity_media_path),
        ),
        migrations.AlterField(
            model_name='charity',
            name='gratitude_card',
            field=models.FileField(blank=True, help_text='Gratitude card (Video or Image)', null=True, upload_to=charity.utils.media_utils.get_charity_media_path),
        ),
    ]
