# Generated by Django 6.0.2 on 2026-03-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0074_alter_campaign_charity_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charity",
            name="billing_address",
        ),
        migrations.AddField(
            model_name="charity",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
