# Generated by Django 6.0.2 on 2026-03-13 22:43

import charity.utils.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0075_add_city_remove_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='video_template_override',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='voiceover_script_override',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='default_template_video',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='default_voice_id',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='default_voiceover_script',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='gratitude_card',
        ),
        migrations.AddField(
            model_name='campaign',
            name='base_video',
            field=models.FileField(blank=True, help_text='Base template video for personalised (TTS+stitch) campaigns', null=True, upload_to=charity.utils.media_utils.get_charity_media_path),
        ),
        migrations.AddField(
            model_name='campaign',
            name='voice_id',
            field=models.CharField(blank=True, help_text='ElevenLabs voice ID for this campaign', max_length=128),
        ),
        migrations.AddField(
            model_name='campaign',
            name='voiceover_script',
            field=models.TextField(blank=True, help_text='Voiceover script with {{donor_name}}, {{donation_amount}}, {{charity_name}} placeholders'),
        ),
    ]
