# Generated by Django 6.0.2 on 2026-03-13 23:13

from django.db import migrations, models


def populate_campaign_mode(apps, schema_editor):
    """Derive campaign_mode from the old campaign_type + video_mode fields."""
    Campaign = apps.get_model("charity", "Campaign")
    for campaign in Campaign.objects.all():
        campaign_type = campaign.campaign_type or ""
        video_mode = campaign.video_mode or ""
        if campaign_type == "VDM":
            campaign.campaign_mode = "VDM"
        elif video_mode == "TEMPLATE":
            campaign.campaign_mode = "THANK_YOU_STANDARD"
        else:
            # Default: THANK_YOU with no/unknown video_mode → PERSONALIZED
            campaign.campaign_mode = "THANK_YOU_PERSONALIZED"
        campaign.save(update_fields=["campaign_mode"])


def reverse_populate_campaign_mode(apps, schema_editor):
    """Reverse: derive campaign_type + video_mode from campaign_mode."""
    Campaign = apps.get_model("charity", "Campaign")
    for campaign in Campaign.objects.all():
        mode = campaign.campaign_mode or ""
        if mode == "VDM":
            campaign.campaign_type = "VDM"
            campaign.input_source = "CSV"
            campaign.video_mode = "TEMPLATE"
        elif mode == "THANK_YOU_STANDARD":
            campaign.campaign_type = "THANK_YOU"
            campaign.input_source = "CSV"
            campaign.video_mode = "TEMPLATE"
        else:
            campaign.campaign_type = "THANK_YOU"
            campaign.input_source = "CSV"
            campaign.video_mode = "PERSONALIZED"
        campaign.save(update_fields=["campaign_type", "input_source", "video_mode"])


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0076_campaign_voice_id_rename_video_fields_remove_charity_defaults"),
    ]

    operations = [
        # Step 1: Add campaign_mode (null=True initially so existing rows are valid)
        migrations.AddField(
            model_name="campaign",
            name="campaign_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("THANK_YOU_PERSONALIZED", "Thank You \u2014 Personalized (TTS + stitch)"),
                    ("THANK_YOU_STANDARD", "Thank You \u2014 Standard (pre-rendered)"),
                    ("VDM", "Video Direct Mail"),
                ],
                help_text=(
                    "How this campaign delivers video. "
                    "Thank You \u2014 Personalized: TTS voiceover + per-donor video stitch. "
                    "Thank You \u2014 Standard: pre-rendered template video, personalised email. "
                    "VDM: shared campaign video sent to all donors (CSV only)."
                ),
                max_length=30,
                null=True,
            ),
        ),
        # Step 2: Populate campaign_mode from the old fields (before they are removed)
        migrations.RunPython(populate_campaign_mode, reverse_populate_campaign_mode),
        # Step 3: Remove the old fields
        migrations.RemoveField(
            model_name="campaign",
            name="campaign_type",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="input_source",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="video_mode",
        ),
    ]
