# Generated by Django 6.0.2 on 2026-03-13 23:46

import datetime

from django.db import migrations, models


def preserve_manual_closes(apps, schema_editor):
    """
    For campaigns that were manually set to 'closed' before their campaign_end date,
    backdate campaign_end to yesterday so the date-derived status stays 'closed'.
    """
    Campaign = apps.get_model("charity", "Campaign")
    today = datetime.date.today()
    yesterday = today - datetime.timedelta(days=1)
    Campaign.objects.filter(
        status="closed",
        campaign_end__gte=today,
    ).update(campaign_end=yesterday)


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0077_replace_campaign_type_with_campaign_mode"),
    ]

    operations = [
        migrations.RunPython(preserve_manual_closes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="campaign",
            name="status",
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_paused",
            field=models.BooleanField(
                default=False,
                help_text="Manually suspend this campaign regardless of dates. Paused campaigns are treated as closed for donation ingestion.",
            ),
        ),
    ]
