# Generated by Django 6.0.2 on 2026-03-14 00:36

from django.db import migrations, models

import charity.utils.media_utils


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0078_date_driven_campaign_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="text_template",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="video_template",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="gratitude_video_template",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="charity_video",
            new_name="vdm_video",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="vdm_email_body",
            new_name="email_body",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="email_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional email body copy for this campaign. Supports {{ donor_name }}, {{ charity_name }}, {{ campaign_name }}, and {{ donation_amount }} placeholders. Leave blank to use the built-in default copy for this campaign mode.",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="vdm_video",
            field=models.FileField(
                blank=True,
                help_text="VDM campaign video — the same video is sent to every donor in the batch.",
                null=True,
                upload_to=charity.utils.media_utils.get_charity_media_path,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="base_video",
            field=models.FileField(
                blank=True,
                help_text="Thank You campaign video. Standard mode: the finished video sent directly to donors. Personalized mode: the base video that TTS audio is stitched onto.",
                null=True,
                upload_to=charity.utils.media_utils.get_charity_media_path,
            ),
        ),
        migrations.DeleteModel(
            name="TextTemplate",
        ),
        migrations.DeleteModel(
            name="VideoTemplate",
        ),
    ]
