# Generated by Django 6.0.2 on 2026-03-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0079_remove_campaign_text_template_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignField',
        ),
    ]
