# Generated by Django 6.0.2 on 2026-03-14 21:58

import charity.utils.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0080_delete_campaignfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional charity logo used in settings previews and donor emails', null=True, upload_to=charity.utils.media_utils.get_charity_media_path),
        ),
    ]
