# Generated by Django 6.0.2 on 2026-03-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0081_charity_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_subject',
            field=models.CharField(blank=True, default='', help_text='Optional email subject for this campaign. Supports {{ donor_name }}, {{ charity_name }}, {{ campaign_name }}, and {{ donation_amount }} placeholders. Leave blank to use the campaign name.', max_length=255),
        ),
    ]
