# Generated by Django 6.0.2 on 2026-03-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0082_campaign_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationjob',
            name='donor_first_name',
            field=models.CharField(blank=True, default='', help_text='Optional donor first name captured from structured import data.', max_length=255),
        ),
        migrations.AddField(
            model_name='donationjob',
            name='donor_last_name',
            field=models.CharField(blank=True, default='', help_text='Optional donor last name captured from structured import data.', max_length=255),
        ),
        migrations.AddField(
            model_name='donationjob',
            name='donor_title',
            field=models.CharField(blank=True, default='', help_text='Optional donor title captured from structured import data.', max_length=50),
        ),
    ]
