# Generated by Django 6.0.2 on 2026-03-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0083_donationjob_donor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cta_message',
            field=models.TextField(blank=True, default='', help_text='Optional body copy shown in the post-video CTA overlay. Supports {{ donor_name }}, {{ charity_name }}, {{ campaign_name }}, and {{ donation_amount }} placeholders. Leave blank to use the built-in default message.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cta_title',
            field=models.CharField(blank=True, default='', help_text='Optional headline shown in the post-video CTA overlay. Supports {{ donor_name }}, {{ charity_name }}, {{ campaign_name }}, and {{ donation_amount }} placeholders. Leave blank to use the built-in default headline.', max_length=255),
        ),
    ]
